#!/bin/sh
# Railway-optimized entrypoint for OpenEMR
# Wraps the standard openemr.sh with Railway-specific configuration
set -e

echo "======================================"
echo "OpenEMR Railway Deployment"
echo "======================================"
echo ""

# Railway-specific: Parse MySQL URL if provided via DATABASE_URL
# Railway's MySQL addon provides DATABASE_URL in the format: mysql://user:password@host:port/database
if [ -n "${DATABASE_URL}" ] && [ -z "${MYSQL_HOST}" ]; then
    echo "Parsing DATABASE_URL for MySQL configuration..."
    
    # Remove mysql:// prefix
    DB_URL_CLEAN=$(echo "${DATABASE_URL}" | sed 's|mysql://||')
    
    # Extract user (everything before the first :)
    MYSQL_USER=$(echo "${DB_URL_CLEAN}" | cut -d':' -f1)
    
    # Extract password (between first : and @)
    MYSQL_ROOT_PASS=$(echo "${DB_URL_CLEAN}" | sed 's|[^:]*:\([^@]*\)@.*|\1|')
    MYSQL_PASS="${MYSQL_ROOT_PASS}"
    
    # Extract host (between @ and the port :)
    MYSQL_HOST=$(echo "${DB_URL_CLEAN}" | sed 's|[^@]*@\([^:]*\):.*|\1|')
    
    # Extract port (between host : and /)
    MYSQL_PORT=$(echo "${DB_URL_CLEAN}" | sed 's|[^@]*@[^:]*:\([0-9]*\)/.*|\1|')
    
    # Extract database (after the /)
    MYSQL_DATABASE=$(echo "${DB_URL_CLEAN}" | sed 's|.*/||' | cut -d'?' -f1)
    
    export MYSQL_HOST MYSQL_USER MYSQL_ROOT_PASS MYSQL_PASS MYSQL_PORT MYSQL_DATABASE
    echo "MySQL Host: ${MYSQL_HOST}"
    echo "MySQL Port: ${MYSQL_PORT}"
    echo "MySQL Database: ${MYSQL_DATABASE}"
    echo "MySQL User: ${MYSQL_USER}"
fi

# Alternatively, Railway MySQL addon provides these individual variables
if [ -n "${MYSQLHOST}" ] && [ -z "${MYSQL_HOST}" ]; then
    echo "Using Railway MySQL environment variables..."
    export MYSQL_HOST="${MYSQLHOST}"
    export MYSQL_PORT="${MYSQLPORT:-3306}"
    export MYSQL_USER="${MYSQLUSER:-root}"
    export MYSQL_ROOT_PASS="${MYSQLPASSWORD}"
    export MYSQL_PASS="${MYSQLPASSWORD}"
    export MYSQL_DATABASE="${MYSQLDATABASE:-openemr}"
    echo "MySQL Host: ${MYSQL_HOST}"
    echo "MySQL Port: ${MYSQL_PORT}"
    echo "MySQL Database: ${MYSQL_DATABASE}"
fi

# Set defaults for OpenEMR admin user if not provided
export OE_USER="${OE_USER:-admin}"
export OE_PASS="${OE_PASS:-pass}"

# Ensure MYSQL_ROOT_PASS is set (required for auto-config)
if [ -z "${MYSQL_ROOT_PASS}" ] && [ -n "${MYSQL_PASS}" ]; then
    export MYSQL_ROOT_PASS="${MYSQL_PASS}"
fi

echo ""
echo "Configuration:"
echo "  MySQL Host: ${MYSQL_HOST:-not set}"
echo "  MySQL Port: ${MYSQL_PORT:-3306}"
echo "  MySQL Database: ${MYSQL_DATABASE:-openemr}"
echo "  OpenEMR Admin User: ${OE_USER}"
echo ""

if [ -z "${MYSQL_HOST}" ]; then
    echo "WARNING: MYSQL_HOST not set. OpenEMR will require manual setup."
    echo "Set DATABASE_URL or individual MySQL env vars for auto-configuration."
    echo ""
fi

# Check if we should do manual setup or auto setup
if [ "${MANUAL_SETUP}" = "yes" ]; then
    echo "MANUAL_SETUP=yes - Skipping auto-configuration"
    echo "Visit the web interface to complete setup."
    echo ""
fi

# ============================================================
# Railway-specific: Check if database already has tables
# This prevents the "table already exists" crash on container restart
# ============================================================
SITES_DIR="/var/www/localhost/htdocs/openemr/sites/default"
SQLCONF_FILE="${SITES_DIR}/sqlconf.php"

check_database_exists() {
    if [ -z "${MYSQL_HOST}" ] || [ -z "${MYSQL_DATABASE}" ]; then
        return 1
    fi
    
    # Wait for MySQL to be ready (max 30 seconds)
    echo "Checking MySQL connectivity..."
    for i in $(seq 1 30); do
        if mysql -h "${MYSQL_HOST}" -P "${MYSQL_PORT:-3306}" -u "${MYSQL_USER}" -p"${MYSQL_PASS}" \
            -e "SELECT 1" "${MYSQL_DATABASE}" >/dev/null 2>&1; then
            echo "MySQL is ready."
            break
        fi
        echo "Waiting for MySQL... ($i/30)"
        sleep 1
    done
    
    # Check if the users table exists (core OpenEMR table)
    TABLE_EXISTS=$(mysql -h "${MYSQL_HOST}" -P "${MYSQL_PORT:-3306}" -u "${MYSQL_USER}" -p"${MYSQL_PASS}" \
        -N -e "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='${MYSQL_DATABASE}' AND table_name='users';" 2>/dev/null || echo "0")
    
    if [ "$TABLE_EXISTS" = "1" ]; then
        return 0
    fi
    return 1
}

create_site_config() {
    echo "Creating site configuration files for existing database..."
    
    # Ensure sites directory exists
    mkdir -p "${SITES_DIR}"
    
    # Create sqlconf.php with the database credentials
    cat > "${SQLCONF_FILE}" << SQLCONF
<?php
// OpenEMR database configuration
// Auto-generated by Railway entrypoint for existing database
\$host = '${MYSQL_HOST}';
\$port = '${MYSQL_PORT:-3306}';
\$login = '${MYSQL_USER}';
\$pass = '${MYSQL_PASS}';
\$dbase = '${MYSQL_DATABASE}';

\$config = 1;

// Note: disable_utf8_flag should remain false for proper UTF-8 support
\$disable_utf8_flag = false;
SQLCONF

    chmod 644 "${SQLCONF_FILE}"
    echo "Created ${SQLCONF_FILE}"
    
    # Create config.php (required by OpenEMR globals.php)
    CONFIG_FILE="${SITES_DIR}/config.php"
    cat > "${CONFIG_FILE}" << CONFIG
<?php
// OpenEMR site configuration
// Auto-generated by Railway entrypoint for existing database

// Site ID
\$openemr_name = 'OpenEMR';

// Site-specific settings
\$GLOBALS['site_id'] = 'default';

// Include the main sqlconf
require_once(dirname(__FILE__) . '/sqlconf.php');
CONFIG

    chmod 644 "${CONFIG_FILE}"
    echo "Created ${CONFIG_FILE}"
    
    # Create required subdirectories
    mkdir -p "${SITES_DIR}/documents"
    mkdir -p "${SITES_DIR}/era"
    mkdir -p "${SITES_DIR}/edi"
    mkdir -p "${SITES_DIR}/letter_templates"
    echo "Created required subdirectories"
}

# Check if site configuration files exist
CONFIG_FILE="${SITES_DIR}/config.php"

if [ ! -f "${SQLCONF_FILE}" ]; then
    echo ""
    echo "No sqlconf.php found - checking if database is already initialized..."
    
    if check_database_exists; then
        echo ""
        echo "======================================"
        echo "EXISTING DATABASE DETECTED"
        echo "======================================"
        echo "Database '${MYSQL_DATABASE}' already contains OpenEMR tables."
        echo "Creating configuration to connect to existing database..."
        echo ""
        
        create_site_config
        
        # Also set EMPTY env var to prevent auto_configure from running
        export EMPTY="yes"
        
        echo "Database recovery complete. OpenEMR will use existing data."
        echo ""
    else
        echo "No existing database found - will run normal setup."
    fi
elif [ ! -f "${CONFIG_FILE}" ]; then
    # sqlconf.php exists but config.php is missing - create it
    echo "sqlconf.php exists but config.php is missing - creating it..."
    
    # Create config.php (required by OpenEMR globals.php)
    cat > "${CONFIG_FILE}" << CONFIG
<?php
// OpenEMR site configuration
// Auto-generated by Railway entrypoint for existing database

// Site ID
\$openemr_name = 'OpenEMR';

// Site-specific settings
\$GLOBALS['site_id'] = 'default';

// Include the main sqlconf
require_once(dirname(__FILE__) . '/sqlconf.php');
CONFIG

    chmod 644 "${CONFIG_FILE}"
    echo "Created ${CONFIG_FILE}"
    
    # Ensure required subdirectories exist
    mkdir -p "${SITES_DIR}/documents"
    mkdir -p "${SITES_DIR}/era"
    mkdir -p "${SITES_DIR}/edi"
    mkdir -p "${SITES_DIR}/letter_templates"
else
    echo "Site configuration exists - using existing configuration."
fi

echo "======================================"
echo "Starting OpenEMR..."
echo "======================================"
echo ""
echo "Default credentials (if auto-configured):"
echo "  Username: ${OE_USER}"
echo "  Password: ${OE_PASS}"
echo ""
echo "IMPORTANT: Change these credentials immediately after login!"
echo ""

# Execute the standard OpenEMR entrypoint
# Redirect stderr to stdout to prevent progress indicators from being logged as errors
# OpenEMR's setup script writes progress dots/pluses to stderr, which Railway logs as errors
cd /var/www/localhost/htdocs/openemr
exec ./openemr.sh 2>&1
